Added delay & scramble features
henriquehbr/svelte-typewriter pull request #17
Opened 2020-09-07 05:11 UTC by BerkinAKKAYA

2020-09-07 14:05 UTC, BerkinAKKAYA commented
I improved the algorithm a bit and created [this effect](https://berkinakkaya.github.io/you-have-been-hacked), i think it turned out pretty good! Thanks for the component!

2020-09-07 14:25 UTC, henriquehbr commented
This one looks truly amazing! great job 👏🏻  

I'm looking forward to review this once i finish some modularization work, in short, the project in it's actual state needs a more scalable structure, both in terms of performance and maintainability, instead of writing everything in a single component

In case you wanna read more about this issue, check out #15

2020-09-07 17:53 UTC, BerkinAKKAYA commented
@henriquehbr I'm glad you liked! I will be following this project closely. It helped me learn a lot about component development already. I would love to contribute more if i can. Good luck!

2020-09-13 02:05 UTC, henriquehbr requested changes

2020-09-13 02:05 UTC, henriquehbr commented on Typewriter.svelte
> +			if (loop) {
Probably that's a personal preference, but doesn't a `switch` statement fits better here?

```js
switch (true) {
    case loop:
        loopMode()
        break
    case scramble:
        scrambleMode()
        break
    default:
        nonLoopMode()
}
```

2020-09-13 02:05 UTC, henriquehbr commented on Typewriter.svelte
> +		const lastElementToFinish = elements.sort((a, b) => b.length - a.length)[0].currentNode;
Avoid using semicolons, please

2020-09-13 07:08 UTC, BerkinAKKAYA reviewed
The changes you requested are done!

**EDIT:** I reverted from `switch` statement back to `if` because if we use `switch` we have to use `scramble !== false` and it looks uglier. Otherwise you can't assign a number to the `scramble` (it's used to define a `maximum scramble count`)

2020-09-15 00:48 UTC, henriquehbr requested changes

2020-09-15 00:48 UTC, henriquehbr commented on Typewriter.svelte
> -	const typingInterval = async () => sleep(interval[rng(0, interval.length)] || interval)
I don't think `typingInterval` can be replaced by `sleep` (as well, `rng` can't be removed, for being it's dependency), otherwise, it would be breaking an already existing feature (#4)

> If an array of numbers is passed to the `interval` prop, the animation will randomly apply a interval from the array for each letter of the text, to mimic a human typing feel

2020-09-15 12:01 UTC, BerkinAKKAYA commented on Typewriter.svelte
> -	const typingInterval = async () => sleep(interval[rng(0, interval.length)] || interval)
I didn't even realize that feature exists, sorry! I removed them because `interval[rng(0, interval.length)]` was always returning `undefined`. I added them back now.

2020-10-06 22:46 UTC, henriquehbr commented
Due to some recent changes that really affected the project architecture (#18), i'm moving both delay (#20) and scramble into different PR's updated with the most recent changes (as it would be impractical and time consuming to just resolve all the conflicts between this branch and `main`)

I will try maintain all the additions as-is, accordingly to this implementation, making changes and refactoring only when needed

2020-10-21 00:52 UTC, henriquehbr commented
I'll be closing this PR, as both features have been already implemented, tested and published on version `2.3.0`, many thanks for your time and effort @BerkinAKKAYA 

By the way, your demo looked so cool, that i decided to include it on a [tweet](https://twitter.com/hbr_henrique/status/1318713996103602183) about the latest release, if you don't mind 😁

2020-10-21 00:52 UTC, closed without merging

2020-10-21 18:10 UTC, BerkinAKKAYA commented
> I'll be closing this PR, as both features have been already implemented, tested and published on version `2.3.0`, many thanks for your time and effort @BerkinAKKAYA
> 
> By the way, your demo looked so cool, that i decided to include it on a [tweet](https://twitter.com/hbr_henrique/status/1318713996103602183) about the latest release, if you don't mind 😁

Thanks for mentioning me, i am so glad to see that 😄